---
apiVersion: bitnami.database.tanzu.vmware.com/v1alpha1
kind: MySQLInstance
metadata:
  name: my-db
spec:
  storageGB: 1
---
apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: where-for-dinner-availability-mysql
spec:
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: spring-music
  serviceRef:
    apiGroup: bitnami.database.tanzu.vmware.com
    kind: MySQLInstance
    name: my-db
  alias: db
